# Don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Set window and pane to start with index 1
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows after one is closed
set -g renumber-windows on

# Keep the current path when creating a new window
bind c new-window -c "#{pane_current_path}"

# Reload tmux config with Prefix + r and display "Reloaded!" message
bind r source-file ~/.tmux.conf \; display " Reloaded!"

# Panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# Statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left '  #S '
set -g status-left-style 'fg=black bg=blue'

set -g status-right "  #(basename $(pwd)) "
set -g status-right-style 'fg=black bg=blue'

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I  #W '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W '

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# Messages
set -g message-style 'fg=black bg=yellow'

# tmux colors
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
